name: AIO App CI

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master
  release:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['12', '10']
        os: [macOS-10.14, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup CLI
        uses: sandeep-paliwal/aio-cli-setup@0.0.2
      - name: npm install
        run: npm i
      - name: Build
        uses: sandeep-paliwal/aio-app@0.0.3
        with:
          command: build
          AIO_RUNTIME_NAMESPACE: ${{ secrets.AIO_RUNTIME_NAMESPACE }}
      - name: Test
        uses: sandeep-paliwal/aio-app@0.0.4
        with:
          command: test
      - name: Deploy
        uses: sandeep-paliwal/aio-app@0.0.4
        with:
          command: deploy
          AIO_RUNTIME_AUTH: ${{ secrets.AIO_RUNTIME_AUTH }}
          AIO_RUNTIME_NAMESPACE: ${{ secrets.AIO_RUNTIME_NAMESPACE }}
